server:
    port: 8080
    host: 127.0.0.1

database:
    host: 127.0.0.1
    port: 5432
    dbname: aio
    schema: aio
    string_len: 100
    hash_len: 512
    token_len: 128
    salt_len: 64
    currency_acc: [10, 2]
    token_time: 3600

